<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '16',
    'typeid' => '0',
    'title' => '迪奥烈艳蓝金唇膏',
    'style' => '',
    'thumb' => 'http://localhost/scmakeup/uploadfile/2014/0304/20140304055359264.png',
    'keywords' => '迪奥烈 艳 蓝',
    'description' => '迪奥烈艳蓝金唇膏',
    'posids' => '0',
    'url' => 'http://localhost/scmakeup/index.php?m=content&c=index&a=show&catid=16&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1393926826',
    'updatetime' => '1393926849',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '16',
    'typeid' => '0',
    'title' => '订制色彩，柔奢宠护',
    'style' => '',
    'thumb' => 'http://localhost/scmakeup/uploadfile/2014/0304/20140304055537728.png',
    'keywords' => '订制 色彩 ，',
    'description' => '订制色彩，柔奢宠护',
    'posids' => '0',
    'url' => 'http://localhost/scmakeup/index.php?m=content&c=index&a=show&catid=16&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1393926927',
    'updatetime' => '1393926972',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '16',
    'typeid' => '0',
    'title' => '指甲油',
    'style' => '',
    'thumb' => 'http://localhost/scmakeup/uploadfile/2014/0304/20140304060125860.png',
    'keywords' => '指甲油',
    'description' => '指甲油',
    'posids' => '0',
    'url' => 'http://localhost/scmakeup/index.php?m=content&c=index&a=show&catid=16&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1393927269',
    'updatetime' => '1393927316',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>